### ISSUE TITLE
Player tracker crafting not working

### ISSUE THREAD

**Issue by Chaikenji** [ILikeFood971/ForF#4]
Error receiving packet 109
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2520.method_23258()" because "$$0" is null

**Comment by ILikeFood971** [comment]
Could you please send a log from both the server and client when the error occurs?

**Comment by ILikeFood971** [comment]
It has been 2 months since this was opened and I haven't been able to reproduce. Without any further information I'm going to consider this either fixed or not related to ForF.
